---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  labels:
    run: hello-k8s
spec:
  type: NodePort
  ports: 
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector: 
    run: hello-k8s
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-k8s
  labels:
    run: hello-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        run: hello-k8s
    spec:
      containers:
      - name: http
        image: nginx
        ports:
        - containerPort: 80
