Master:

  Image: "jenkinsci/jenkins"
  ImageTag: "lts"
  UseSecurity: false
  Master.resources: {requests: {cpu: 50m, memory: 512Mi}, limits: {cpu: 2000m, memory: 2048Mi}}
  ServiceType: NodePort
  NodePort: 31111

  InstallPlugins:
    - kubernetes:1.12.0
    - workflow-aggregator:2.5
    - workflow-job:2.23
    - git:3.9.1

Agent:
  Enabled: true

  Image: radumatei/jenkins-slave-docker
  ImageTag: kubectl
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
    - type: HostPath
      hostPath: /root/.kube
      mountPath: /root/.kube

rbac:
  install: false
