Master:

  Image: "jenkinsci/jenkins"
  ImageTag: "lts"
  UseSecurity: false
  Master.resources: {requests: {cpu: 500m, memory: 1024Mi}, limits: {cpu: 2000m, memory: 2048Mi}}
  ServiceType: NodePort
  NodePort: 31111

  InstallPlugins:
    - job-restrictions:0.8
    - kubernetes:1.12.7
    - pipeline-maven:3.5.14
    - workflow-aggregator:2.5
    - workflow-job:2.23
    - git:3.9.1

Agent:
  Enabled: true

  Image: cloudbees/jnlp-slave-with-java-build-tools
  ImageTag: latest
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
    - type: HostPath
      hostPath: /root/.kube
      mountPath: /root/.kube

rbac:
  install: false
